import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { UIStateProvider } from "@/components/providers/ui-state";
import { Navbar } from "@/components/navbar";
import "./globals.css";
import "highlight.js/styles/github.css";
import { DocsProvider } from "@/components/providers/docs-provider";
import { Sidebar } from "@/components/sidebar";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app" };

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <UIStateProvider>
            <DocsProvider>
              <Navbar />
              <div className="flex">
                <Sidebar />
                <div className="flex-1">{children}</div>
              </div>
            </DocsProvider>
          </UIStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
