import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { UIStateProvider } from '@/components/providers/ui-state';
import { Navbar } from '@/components/navbar';
import './globals.css';
import 'highlight.js/styles/github.css';
import { DocsProvider } from '@/components/providers/docs-provider';
import { MobileSidebar, Sidebar } from '@/components/sidebar';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = { title: 'Create Next App', description: 'Generated by create next app' };

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <UIStateProvider>
            <DocsProvider>
              {/* NAVBAR FIJO */}
              <div className="fixed inset-x-0 top-0 z-50 h-[var(--navbar-h)]">
                <Navbar />
              </div>

              {/* Drawer móvil del sidebar */}
              <MobileSidebar />

              {/* CONTENIDO BAJO EL NAVBAR */}
              <div className="pt-[var(--navbar-h)] min-h-screen">
                <div className="grid grid-cols-1 md:grid-cols-[260px_1fr]">
                  {/* SIDEBAR STICKY */}
                  <aside
                    className="
                    hidden md:block
                    sticky top-[var(--navbar-h)]
                    h-[calc(100vh-var(--navbar-h))]
                    overflow-y-auto border-r
                  "
                  >
                    <Sidebar />
                  </aside>

                  {/* MAIN SCROLLEABLE */}
                  <main className="min-h-[calc(100vh-var(--navbar-h))] overflow-y-auto">{children}</main>
                </div>
              </div>
            </DocsProvider>
          </UIStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
